# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="minetech"
version="${file.jarVersion}"
displayName="Minetech"
credits="The Minetech dev team"
authors="RoBaertschi"
description='''
A GregTech inspired Tech mod for modern Minecraft!
'''
[[dependencies.minetech]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.minetech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
